# fly.toml app configuration file generated for linearcool on 2023-08-28T22:04:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linearcool"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
